BoutiqueVehicles = {
   {label = 'Audi RS3 2022', model = 'rs322', description = nil, price = 1500},
   {label = 'MERCEDES GLE53', model = 'gle53', description = nil, price = 2500},
  -- {label = 'DODGE CHARGER HELLCA', model = 'charger21', description = nil, price = 3000},
   {label = 'MERCEDES G500', model = 'brabus500', description = nil, price = 2500},
   {label = 'RANGE ROVER SPORT', model = 'rmodrover', description = nil, price = 3000},
   {label = 'AUDI RS6', model = '2020RS6', description = nil, price = 2500},
   {label = 'AUDI RS7', model = 'rs7r', description = nil, price = 2500},
   {label = 'JEEP TRACKHAWK', model = 'trhawk', description = nil, price = 2000},
   {label = 'ROLLS ROYCE CULLINAN', model = 'cullinann', description = nil, price = 3000},
   {label = 'BMW M8', model = 'bmwm8wb', description = nil, price = 3000},
   {label = 'MV AGUSTA', model = 'f4rr', description = nil, price = 1500},
   {label = 'MERCEDES G650', model = 'g650', description = nil, price = 2500},
   {label = 'CHEVROLET TAHOE', model = 'tahoe21', description = nil, price = 3000},
   {label = 'PORSCHE 918', model = '918', description = nil, price = 4800},
   {label = 'BENTLEY BENTAYGA', model = 'bentaygam', description = nil, price = 2500},
   {label = 'AUDI RS666', model = 'rs666', description = nil, price = 3500},
   {label = 'BUGATTI CHIRON SS', model = 'chironss', description = nil, price = 4800},
   {label = 'LAMBO AVENTADOR SV', model = 'rmodlp750', description = nil, price = 4000},
   {label = 'MERCEDES E63S', model = 'e63sf', description = nil, price = 2000},
   {label = 'Golf 7R', model = 'mk7', description = nil, price = 1500},
   {label = 'AUDI RS7 C8WB', model = 'rs7c8wb', description = nil, price = 3000},
   {label = 'MERCEDES GLS', model = 'gls20', description = nil, price = 2400},
   {label = 'FORD MUSTANG', model = 'mustang19', description = nil, price = 2400},
   {label = 'LAMBORGHINI SIAN', model = 'rmodsianr', description = nil, price = 4200},
   {label = 'Honda 450CRF', model = '450crf', description = nil, price = 2000},
   {label = 'Yamaha R1 2020', model = 'r1', description = nil, price = 2400},
   {label = 'TMAX', model = 'tmaxdx', description = nil, price = 1000},
   {label = 'Peugeot 205 Turbo', model = 'yPG205t16A', description = nil, price = 1500},
   {label = 'Lamborghini Huracan', model = 'hurevos', description = nil, price = 4000},
   {label = 'Fiat Abart', model = 'rmodbiposto', description = nil, price = 2000},
   {label = 'Renault Clio RS', model = 'cliors', description = nil, price = 1500},
   {label = 'Urus 2018', model = 'urus', description = nil, price = 2000},
   {label = 'Toyota Supra', model = 'rmodsuprapandem', description = nil, price = 2500},
   {label = 'Formule 1', model = 'rb18', description = nil, price = 2000},
   {label = 'BMW M2', model = '22m2cs', description = nil, price = 2000},
   {label = 'Audi TT', model = 'ttsr', description = nil, price = 2500},
   {label = 'Tesla ModelS', model = 'teslapd', description = nil, price = 5000},
   {label = 'Golf 8 GTI', model = 'mk8r', description = nil, price = 3000},
   {label = 'FORD RAPTOR', model = 'RAPTOR150', description = nil, price = 2500},
   {label = 'Audi s3 2015', model = '2015s3', description = nil, price = 3500},
   {label = 'Ferrari 488', model = '488', description = nil, price = 2500},
   {label = 'BMW 745le', model = '745le', description = nil, price = 1300},
   {label = 'Porsche 911 turbo S', model = '911turbos', description = nil, price = 4000},
   {label = 'Rolls-Royce', model = 'bbdawn', description = nil, price = 2000},
   {label = 'Porsche Cayenne turbo', model = 'cayenneturbo', description = nil, price = 2500},
   {label = 'Rolls-Royce', model = 'bbdawn', description = nil, price = 2000},
   {label = 'Suzuki Ninja 2', model = 'ninjah2', description = nil, price = 1500},
   {label = 'McLaren p1', model = 'p1', description = nil, price = 5000},
   {label = 'Rolls-Royce phantom', model = 'phantom8', description = nil, price = 3000},
   {label = 'Mercedes c63 amg', model = 'rmodc63amg', description = nil, price = 3000},
   {label = 'Mercedes gt63 s', model = 'rmodgt63', description = nil, price = 3000},
   {label = 'BMW m4 gts', model = 'rmodm4gts', description = nil, price = 1500},
   {label = 'Audi rs5', model = 'rs5r', description = nil, price = 3000},
   {label = 'Mercedes amg 6x6', model = 'g63amg6x6', description = nil, price = 3500},
   {label = 'Mercedes E 63amg', model = 'e63amg', description = nil, price = 3000},
   {label = 'Tesla', model = 'tesroad20', description = nil, price = 3000},
   {label = 'Audi RS6 abt', model = 'rs6avant20', description = nil, price = 3000},
   {label = 'Audi r8', model = 'r8ppi', description = nil, price = 3000},
   {label = 'Camion Mercedes', model = 'rtruck', description = nil, price = 2500},
   {label = 'Mercedes g65 amg', model = 'g65amg', description = nil, price = 3000},
   {label = 'Ferrari f488 pista', model = 'f488pista', description = nil, price = 3500},
   {label = 'Tesla Model X' , model = 'teslax', description = nil, price = 3500},
}
 
 BoutiqueAirPlaines = {
     {model = 'microlight', description = nil, price = 750},
     {model = 'havok', description = nil, price = 1000},
     {model = 'stunt', description = nil, price = 1250},
     {model = 'buzzard2', description = nil, price = 1500},
     {model = 'supervolito2', description = nil, price = 2000},
     {model = 'swift2', description = nil, price = 2500},
     {model = 'luxor2', description = nil, price = 3000},
 }
 
 -- BATEAUX
 
 BoutiqueBoat = {
     {model = 'seashark3', description = nil, price = 750},
     {model = 'submersible', description = nil, price = 1250},
     {model = 'submersible2', description = nil, price = 1500},
     {model = 'longfin', description = nil, price = 2000},
     {model = 'sr650fly', description = nil, price = 2500},
 }
 
 -- ARMES 
 
 WeaponBoutique = {
     --{label = 'Epée en diamant', name = 'WEAPON_HATCHET', description = nil, price = 450},
     --{label = 'Katana', name = 'WEAPON_KATANA', description = nil, price = 450},
     --{label = 'Double Action Revolver', name = 'WEAPON_DOUBLEACTION', description = nil, price = 1000},
     --{label = 'Navy Revolver', name = 'WEAPON_NAVYREVOLVER', description = nil, price = 1250},
     --{label = 'Revolver', name = 'WEAPON_REVOLVER', description = nil, price = 1800},
     --{label = 'Pistolet Cayo', name = 'WEAPON_GADGETPISTOL', description = nil, price = 1500},
     --{label = 'AK-47', name = 'WEAPON_ASSAULTRIFLE', description = nil, price = 2500},
     --{label = 'Arme de Défense Personnel', name = 'WEAPON_COMBATPDW', description = nil, price = 3500},
 }
 
 -- CAISSE MYSTERE
 
 BoutiqueMysteryBox = {
     {label = 'Caisse de ~r~Juin~s~', description = 'Prix : 500 ~q~Sova~w~Coins', model = 'caisse_juin', rightlabel = nil, price = 850},
--     {label = 'Caise ~g~Légendaire~s~', description = 'Prix : 1000 ~q~Sova~w~Coins', model = 'caisse_diamond', rightlabel = nil,  price = 1000},
   --  {label = 'Caisse ~r~Ultime~s~',description = 'Prix : 2500 ~q~Sova~w~Coins', model = 'caisse_ruby', rightlabel = nil,  price = 2500},
     --{label = 'Caisse ~q~No~s~ël', description = 'Prix : 1500 ~q~Sova~w~Coins', model = 'caisse_noel',rightlabel = nil, price = 1500},
     --{label = 'Caisse Halloween', description = 'Prix : 1500 ~q~Sova~w~Coins', model = 'caisse_halloween',rightlabel = nil, price = 1500},
  --   {label = 'Caisse Fidelité', description = 'Obtenable uniquement via le Bonus Fidélité', model = 'caisse_fidelite',rightlabel = nil, price = 9999999}, -- desactiver pour le moment
 --    {label = 'Caisse Véhicule',description = 'Prix : 1750 ~q~Sova~w~Coins', model = 'caisse_vehicule', rightlabel = nil,  price = 1750}
 }
 
 VisualitionCaisse = {
     ['caisse_juin'] = {
        {model = 'money_50000', label = '50000$', rarity = 4},
         {model = 'silv2500hd', label = 'Chevrolet', rarity = 4}, --
         {model = 'Coins_1000', label = '1000 Coins', rarity = 4}, 
         {model = 'weapon_machete', label = 'Katana', rarity = 3}, --
         {model = 'm5e60', label = 'BMW M5 E60', rarity = 3},  --
         {model = 'weapon_vintagepistol', label = 'Pistolet Vintage', rarity = 3},  -- 
         {model = 'money_10000', label = '10000$', rarity = 2},  --
         {model = 'Coins_850', label = '850 Coins', rarity = 2},  
         {model = 'Coins_800', label = '800 Coins', rarity = 2},
         {model = 'supra3', label = 'Supra', rarity = 2},  --
         {model = 'weapon_bottle', label = 'Bouteille cassée', rarity = 1},  --
         {model = 'z419', label = 'BMW Z4', rarity = 1}, -- 
         {model = 'Coins_500', label = '500 Coins', rarity = 1}, 
         {model = 'rmodx6', label = 'BMW X6', rarity = 1},
         {model = 'weapon_golfclub', label = 'Club de golf', rarity = 1}, --
     },
     ['caisse_diamond'] = {
         {model = 'weapon_pumpshotgun', label = 'Fusil a pompe', rarity = 4},
         {model = 'weapon_heavyshotgun', label = 'Fusil a Pompe', rarity = 4},
         {model = 'weapon_appistol', label = 'Pistolet Perforant', rarity = 3},
         {model = 'weapon_assaultrifle', label = 'Fusil d\'assault', rarity = 3},
         {model = 'money_1000000', label = '1000000$', rarity = 2},
         {model = 'Coins_850', label = '850 Coins', rarity = 2},
         {model = 'Coins_500', label = '500 Coins', rarity = 2},
         {model = '918', label = 'Porshe 918 Spyder', rarity = 1},
         {model = 'rmodc63amg', label = 'Mercedes AMG C63', rarity = 1},
         {model = 'chironss', label = 'Bugatti Chiron', rarity = 1},
         {model = 'rmodatlantic', label = 'Bugatti Atlantic', rarity = 1},
         {model = 'rs6avant20', label = 'Audi RS6 2015', rarity = 1},
         {model = 'rs7r', label = 'Audi RS7 R', rarity = 1},
         {model = 'z15326power', label = 'Voiture de Drift', rarity = 1},
         {model = 'ninjah2', label = 'Moto', rarity = 1},
         {model = 'g65amg', label = 'Mecedes G65 AMG', rarity = 1},
         {model = 'huayrar', label = 'Pagani', rarity = 1},
         {model = 'r88pi', label = 'Audi R8 C', rarity = 1},
         {model = 'r8ppi', label = 'Audi RS3 2018', rarity = 1},
         {model = 'bmws19', label = 'Moto', rarity = 1},
         {model = '22m5', label = 'BMW M5', rarity = 1},
         {model = 'brabus500', label = 'Brabus 500', rarity = 1},
         {model = 'g65amg', label = 'Brabus 800', rarity = 1},
     },
     ['caisse_ruby'] = {
         --{model = 'weapon_combatmg_mk2', label = 'Mitrailleuse de Combat MK2', rarity = 4},
         --{model = 'weapon_mg', label = 'Mitailleuse', rarity = 4},
         --{model = 'weapon_combatmg', label = 'Mitrailleuse de Combat', rarity = 4},
         --{model = 'weapon_marksmanrifle_mk2', label = 'Fusil Marskman', rarity = 4},
         {model = 'weapon_assaultshotgun', label = 'Fusil a pompe d\'assault', rarity = 4},
         {model = 'swift2', label = 'Helicoptère de luxe', rarity = 4},
         {model = 'weapon_heavysniper_mk2', label = 'Fusil Sniper Heavy', rarity = 4},
         {model = 'cargobob2', label = 'Cargobob', rarity = 4}, 
         {model = 'luxor2', label = 'Avion de Luxe', rarity = 3},
         {model = 'buzzard2', label = 'Buzzard', rarity = 3},
         
         {model = 'Coins_800', label = '800 Coins', rarity = 1},
         {model = 'Coins_850', label = '850 Coins', rarity = 1},
         {model = 'Coins_1000', label = '1000 Coins', rarity = 1},
         {model = 'BMWS19', label = 'Moto', rarity = 1},
         {model = 'p1', label = 'Mclaren P1', rarity = 1},
         {model = 'rs666', label = 'Audi RS6', rarity = 1},
     },
     ['caisse_noel'] = {
        {model = 'WEAPON_SCAR17FM', label = 'SCAR 17', rarity = 4},
        {model = 'Coins_2250', label = '2250 ~q~Sea~s~Coins', rarity = 4},
        {model = 'WEAPON_SPECIALCARBINE', label = 'Carabine Spéciale', rarity = 4},
        {model = 'WEAPON_COMBATPDW', label = 'ADP de Combat', rarity = 4},
        {model = 'vehicleunique', label = 'Véhicule Unique ( 75€ )', rarity = 4},
        {model = 'cargobob2', label = 'Cargobob', rarity = 4},
        {model = 'WEAPON_ASSAULTRIFLE', label = 'Fusil d\'assault', rarity = 3},
        {model = 'WEAPON_GADGETPISTOL', label = 'Pistolet Cayo', rarity = 3},
        {model = 'WEAPON_SNOWBALL', label = 'Boule de neige', rarity = 3},
        {model = 'Custom_5', label = 'Jeton Custom x5', rarity = 3},
        {model = 'q820', label = 'Audi Q8 2020', rarity = 2},
        {model = 'Custom_3', label = 'Jeton Custom x3', rarity = 2},
        {model = 'WEAPON_CASABLANCA', label = 'Machete Casa Blanca', rarity = 2},
        {model = 'WEAPON_KATANA', label = 'Katana', rarity = 2},
        {model = 'Custom_1', label = 'Jeton Custom x1', rarity = 1},
        {model = 'V250', label = 'Van Mercedes V250', rarity = 1},
        {model = 'GADGET_PARACHUTE', label = 'Parachute', rarity = 1},
        {model = 'survolt', label = 'Citroën Survolt', rarity = 1},
        {model = 'senna', label = 'McLaren Senna', rarity = 1},
        {model = '22M5', label = 'BMW M5 E34', rarity = 1},
        {model = 'acz4', label = 'BMW Z4', rarity = 1},
        {model = 'a80', label = 'Toyota Supra', rarity = 1},
        {model = 'RS5R', label = 'AUDI RS5', rarity = 1},
        {model = '16challenger', label = 'Dodge Challenger', rarity = 1},
        {model = 'R8PPI', label = 'AUDI R8 2020', rarity = 1},
        {model = 'rmodx6', label = 'BMW X6 M', rarity = 1},
     },
     ['caisse_halloween'] = {
         {model = 'dune2', label = 'Voiture Halloween', rarity = 3},
         {model = 'SeaCoins_2500', label = '2500 ~q~Sea~w~Coins', rarity = 3},
         {model = 'speedo2', label = 'Camion Halloween', rarity = 3},
         {model = 'weapon_flaregun', label = 'Flare Gun', rarity = 2},
         {model = 'money_2500000', label = '2500000$', rarity = 2},
         {model = 'money_1500000', label = '1500000$', rarity = 2},
         {model = 'BType2', label = 'BType 2', rarity = 1},
         {model = 'money_750000', label = '750000$', rarity = 1},
         {model = 'Tornado6', label = 'Tornado Halloween', rarity = 1},
     },
     ['caisse_fidelite'] = {
         --{model = 'weapon_combatmg_mk2', label = 'Mitrailleuse de Combat MK2', rarity = 4},
         --{model = 'weapon_mg', label = 'Mitailleuse', rarity = 4},
         --{model = 'weapon_combatmg', label = 'Mitrailleuse de Combat', rarity = 4},
         {model = 'weapon_assaultshotgun', label = 'Fusil a pompe d\'assault', rarity = 4},
         {model = 'weapon_marksmanrifle_mk2', label = 'Fusil Marskman', rarity = 4},
         {model = 'swift2', label = 'Helicoptère de luxe', rarity = 4},
         {model = 'weapon_heavysniper_mk2', label = 'Fusil Sniper Heavy', rarity = 4},
         {model = 'cargobob2', label = 'Cargobob', rarity = 4},
         {model = 'luxor2', label = 'Avion de Luxe', rarity = 3},
         {model = 'buzzard2', label = 'Buzzard', rarity = 3},
         
         {model = 'Coins_800', label = '800 Coins', rarity = 1},
         {model = 'Coins_850', label = '850 Coins', rarity = 1},
         {model = 'Coins_1000', label = '1000 Coins', rarity = 1},
         {model = 'BMWS19', label = 'Moto', rarity = 1},
         {model = 'p1', label = 'Mclaren P1', rarity = 1},
         {model = 'rs666', label = 'Audi RS6', rarity = 1},
         {model = 'gadget_parachute', label = 'Parachute', rarity = 1},
     },
     ['caisse_vehicule'] = {
         {model = 'cooperworks', label = 'Cooper', rarity = 1},
         {model = 'FCT', label = 'Ferrari 2015', rarity = 3},
         {model = 'M3E30', label = 'BMW M3 E30', rarity = 2},
         {model = 'mercxclass', label = 'Mercedes-Benz X-Class', rarity = 2},
         {model = 'Mustang', label = 'Mustang', rarity = 2},
         {model = 'rmodmustang', label = 'Mustang GT', rarity = 3},
         {model = 'TESLAMODELS', label = 'Tesla model S', rarity = 1},
         {model = 'VIPER', label = 'VIPER', rarity = 3},
     },
 }