SecurityVehicles = {
    ['rs322'] = {label = 'Audi RS3 2022', model = 'rs322', description = nil, price = 1500},
    ['gle53'] = {label = 'MERCEDES GLE53', model = 'gle53', description = nil, price = 2500},
   -- ['charger21'] = {label = 'DODGE CHARGER HELLCA', model = 'charger21', description = nil, price = 3000},
    ['brabus500'] = {label = 'MERCEDES G500', model = 'brabus500', description = nil, price = 2500},
    ['rmodrover'] = {label = 'RANGE ROVER SPORT', model = 'rmodrover', description = nil, price = 3000},
    ['2020RS6'] = {label = 'AUDI RS6', model = '2020RS6', description = nil, price = 2500},
    ['rs7r'] = {label = 'AUDI RS7', model = 'rs7r', description = nil, price = 2500},
    ['trhawk'] = {label = 'JEEP TRACKHAWK', model = 'trhawk', description = nil, price = 2000},
    ['cullinann'] = {label = 'ROLLS ROYCE CULLINAN', model = 'cullinann', description = nil, price = 3000},
    ['bmwm8wb'] = {label = 'BMW M8', model = 'bmwm8wb', description = nil, price = 3000},
    ['f4rr'] = {label = 'MV AGUSTA', model = 'f4rr', description = nil, price = 1500},
    ['g650'] = {label = 'MERCEDES G650', model = 'g650', description = nil, price = 2500},
    ['tahoe21'] = {label = 'CHEVROLET TAHOE', model = 'tahoe21', description = nil, price = 3000},
    ['918'] = {label = 'PORSCHE 918', model = '918', description = nil, price = 4800},
    ['bentaygam'] = {label = 'BENTLEY BENTAYGA', model = 'bentaygam', description = nil, price = 2500},
    ['rs666'] = {label = 'AUDI RS666', model = 'rs666', description = nil, price = 3500},
    ['chironss'] = {label = 'BUGATTI CHIRON SS', model = 'chironss', description = nil, price = 4800},
    ['rmodlp750'] = {label = 'LAMBO AVENTADOR SV', model = 'rmodlp750', description = nil, price = 4000},
    ['e63sf'] = {label = 'MERCEDES E63S', model = 'e63sf', description = nil, price = 2000},
    ['mk7'] = {label = 'Golf 7R', model = 'mk7', description = nil, price = 1500},
    ['rs7c8wb'] = {label = 'AUDI RS7 C8WB', model = 'rs7c8wb', description = nil, price = 3000},
    ['gls20'] = {label = 'MERCEDES GLS', model = 'gls20', description = nil, price = 2400},
    ['mustang19'] = {label = 'FORD MUSTANG', model = 'mustang19', description = nil, price = 2400},
    ['rmodsianr'] = {label = 'LAMBORGHINI SIAN', model = 'rmodsianr', description = nil, price = 4200},
    ['450crf'] = {label = 'Honda 450CRF', model = '450crf', description = nil, price = 2000},
    ['r1'] = {label = 'Yamaha R1 2020', model = 'r1', description = nil, price = 2400},
    ['tmaxdx'] = {label = 'TMAX', model = 'tmaxdx', description = nil, price = 1000},
    ['yPG205t16A'] = {label = 'Peugeot 205 Turbo', model = 'yPG205t16A', description = nil, price = 1500},
    ['hurevos'] = {label = 'Lamborghini Huracan', model = 'hurevos', description = nil, price = 4000},
    ['rmodbiposto'] = {label = 'Fiat Abart', model = 'rmodbiposto', description = nil, price = 2000},
    ['cliors'] = {label = 'Renault Clio RS', model = 'cliors', description = nil, price = 1500},
    ['urus'] = {label = 'Urus 2018', model = 'urus', description = nil, price = 2000},
    ['rmodsuprapandem'] = {label = 'Toyota Supra', model = 'rmodsuprapandem', description = nil, price = 2500},
    ['rb18'] = {label = 'Formule 1', model = 'rb18', description = nil, price = 2000},
    ['22m2cs'] = {label = 'BMW M2', model = '22m2cs', description = nil, price = 2000},
    ['ttsr'] = {label = 'Audi TT', model = 'ttsr', description = nil, price = 2500},
    ['teslapd'] = {label = 'Tesla ModelS', model = 'teslapd', description = nil, price = 5000},
    ['mk8r'] = {label = 'Golf 8 GTI', model = 'mk8r', description = nil, price = 3000},
    ['RAPTOR150'] = {label = 'FORD RAPTOR', model = 'RAPTOR150', description = nil, price = 2500},
    ['2015s3'] = {label = 'Audi S3 2015', model = '2015s3', description = nil, price = 3500},
    ['488'] = {label = 'Ferrari 488', model = '488', description = nil, price = 2500},
    ['745le'] = {label = 'BMW 745le', model = '745le', description = nil, price = 1300},
    ['911turbos'] = {label = 'Porsche 911 turbo S', model = '911turbos', description = nil, price = 4000},
    ['bbdawn'] = {label = 'Rolls-Royce', model = 'bbdawn', description = nil, price = 2000},
    ['cayenneturbo'] = {label = 'Porsche Cayenne turbo', model = 'cayenneturbo', description = nil, price = 2500},
    ['ninjah2'] = {label = 'Suzuki ninja 2', model = 'ninjah2', description = nil, price = 1500},
    ['p1'] = {label = 'McLaren p1', model = 'p1', description = nil, price = 5000},
    ['phantom8'] = {label = 'Rolls-Royce phantom', model = 'phantom8', description = nil, price = 3000},
    ['rmodc63amg'] = {label = 'Mercedes c63 amg', model = 'rmodc63amg', description = nil, price = 3000},
    ['rmodgt63'] = {label = 'Mercedes gt63 s', model = 'rmodgt63', description = nil, price = 3000},
    ['rmodm4gts'] = {label = 'BMW m4 gts', model = 'rmodm4gts', description = nil, price = 1500},
    ['rs5r'] = {label = 'Audi rs5', model = 'rs5r', description = nil, price = 3000},
    ['g63amg6x6 '] = {label = 'Mercedes amg 6x6', model = 'g63amg6x6', description = nil, price = 3500},
    ['e63amg'] = {label = 'Mercedes E 63amg', model = 'e63amg', description = nil, price = 3000},
    ['tesroad20'] = {label = 'Tesla', model = 'tesroad20', description = nil, price = 3000},
    ['rs6avant20'] = {label = 'Audi RS6 abt', model = 'rs6avant20', description = nil, price = 3000},
    ['r8ppi'] = {label = 'Audi r8', model = 'r8ppi', description = nil, price = 3000},
    ['rtruck'] = {label = 'Camion Mercedes', model = 'rtruck', description = nil, price = 2500},
    ['g65amg'] = {label = 'Mercedes g65 amg', model = 'g65amg', description = nil, price = 3000},
    ['f488pista'] = {label = 'Ferrari 488 pista', model = 'f488pista', description = nil, price = 3500},
    ['teslax'] = {label = 'Tesla Model X', model = 'teslax', description = nil, price = 3500},
}


SecurityVehiclesPlane = {
    ['microlight'] = {model = 'microlight', price = 750},
    ['stunt'] = {model = 'stunt', price = 1250},
    ['buzzard2'] = {model = 'buzzard2', price = 1500},
    ['supervolito2'] = {model = 'supervolito2', price = 2000},
    ['havok'] = {model = 'havok', price = 1000},
    ['swift2'] = {model = 'swift2', price = 2500},
    ['luxor2'] = {model = 'luxor2', price = 3000},
}

SecurityVehiclesBoat = {
    ['seashark3'] = {model = 'seashark3', price = 750},
    ['submersible'] = {model = 'submersible', price = 1250},
    ['submersible2'] = {model = 'submersible2', price = 1500},
    ['longfin'] = {model = 'longfin', price = 2000},
    ['sr650fly'] = {model = 'sr650fly', price = 2500},
}

-- ARMES 

SecurityWeapons = {
    ['WEAPON_HATCHET'] = {price = 450, name = 'WEAPON_HATCHET', label = 'Epée en diamant'},
    ['WEAPON_BAT'] = {price = 450, name = 'WEAPON_BAT',label = 'Katana'},
    ['WEAPON_DOUBLEACTION'] = {price = 1000, name = 'WEAPON_DOUBLEACTION',label = 'Double Action Revolver'},
    ['WEAPON_NAVYREVOLVER'] = {price = 1250, name = 'WEAPON_NAVYREVOLVER',label = 'Navy Revolver'},
    ['WEAPON_REVOLVER'] = {price = 1800, name = 'WEAPON_REVOLVER',label = 'Revolver'},
    ['WEAPON_ASSAULTRIFLE'] = {price = 2500, name = 'WEAPON_ASSAULTRIFLE',label = 'AK-47'},
    ['WEAPON_COMBATPDW'] = {price = 3500, name = 'WEAPON_COMBATPDW',label = 'Arme de Défense Personnel'},
    ['WEAPON_GADGETPISTOL'] = {price = 1500, name = 'WEAPON_GADGETPISTOL',label = 'Pistolet Cayo'},
}

-- CAISSE MYSTERE

MysteryBox = {
    ListBox = {
        ['caisse_juin'] = {label = 'Caisse Juin', price = 850},
        ['caisse_diamond'] = {label = 'Caise Diamond', price = 1000},
        ['caisse_ruby'] = {label = 'Caisse Ruby', price = 2500},
        ['caisse_noel'] = {label = 'Caisse Noel', price = 1500},
        ['caisse_halloween'] = {label = 'Caisse Halloween', price = 1500},
        ['caisse_fidelite'] = {label = 'Caisse Fidelité', price = 9999999},
        ['caisse_vehicule'] = {label = 'Caisse Véhicule', price = 1750},
    },
    Box = {
        ['caisse_juin'] = {
            [4] = {
                "money_50000",
                "silv2500hd",
                "Coins_1000",
            },
            [3] = {
                "weapon_machete",
                "m5e60",
                "weapon_vintagepistol",
            },
            [2] = {
                "money_10000",
                "Coins_850",
                "Coins_800",
                "supra3",
            },
            [1] = {
                "weapon_bottle",
                "z419",
                "Coins_500",
                "rmodx6",
                "weapon_golfclub",
            },
        },
        ['caisse_diamond'] = {
            [4] = {
                "weapon_pumpshotgun",
                "weapon_heavyshotgun",
            },
            [3] = {
                "weapon_appistol",
                "weapon_assaultrifle",
            },
            [2] = {
                "money_1000000",
                "Coins_850",
                "Coins_500",
            },
            [1] = {
                "918",
                "rmodc63amg",
                "chironss",
                "rmodatlantic",
                "rs615",
                "rs7r",
                "e36drift",
                "ninjah2",
                "huayrar",
                "r8ppi",
                "rs318",
                "bmws19",
                "22m5",
                "brabus500",
                "brabus800",
            },
        },
        ['caisse_ruby'] = {
            [4] = {
                --"weapon_combatmg_mk2",
                --"weapon_mg",
                --"weapon_combatmg",
                "weapon_assaultshotgun",
                "weapon_marksmanrifle_mk2",
                "swift2",
                "weapon_heavysniper_mk2",
                "cargobob2",
                "gls632",
            },
            [3] = {
                "luxor2",
                "buzzard2",
            },
            [2] = {
                "BMWS19",
                "p1",
                "Coins_1000",
            },
            [1] = {
                "Coins_850",
                "Coins_800",
                "rs666",
            },
        },
        ['caisse_noel'] = {
            [4] = {
                "WEAPON_SCAR17FM",
                "Coins_2250",
                "WEAPON_SPECIALCARBINE",
                "WEAPON_COMBATPDW",
                "vehicleunique",
                "cargobob2",
                "gls632",
            },
            [3] = {
                "WEAPON_ASSAULTRIFLE",
                "WEAPON_GADGETPISTOL",
                "WEAPON_SNOWBALL",
                "Custom_5",
            },
            [2] = {
                "q820",
                "Custom_3",
                "WEAPON_CASABLANCA",
                "WEAPON_KATANA",
            },
            [1] = {
                "Custom_1",
                "mb250",
                "GADGET_PARACHUTE",
                "survolt",
                "senna",
                "22m5",
                "acz4",
                "supra3",
                "16challenger",
                "rs62",
                "r820",
                "rmodx6",
            },
        },
        ['caisse_halloween'] = {
            [3] = {
                "dune2",
                "speedo2",
                "Coins_2500"
            },
            [2] = {
                "money_2500000",
                "money_1500000",
                "weapon_flaregun",
            },
            [1] = {
                "BType2",
                "money_750000",
                "Tornado6",
            },
        },
        ['caisse_fidelite'] = {
            [4] = {
                --"weapon_combatmg_mk2",
                --"weapon_mg",
                --"weapon_combatmg",
                "weapon_assaultshotgun",
                "weapon_marksmanrifle_mk2",
                "swift2",
                "weapon_heavysniper_mk2",
                "cargobob2",
                "gls632",
            },
            [3] = {
                "luxor2",
                "buzzard2",
            },
            [2] = {
                "bmws19",
                "p1",
                "Coins_1000",
            },
            [1] = {
                "Coins_850",
                "Coins_800",
                "rs666",
                "gadget_parachute",
            },
        },
        ['caisse_vehicule'] = {
            [4] = {
                "weapon_pistol_mk2",
                "weapon_machinepistol",
                "weapon_stone_hatchet",
            },
            [3] = {
                "FCT",
                "VIPER",
                "Mustang",
            },
            [2] = {
                "M3E30",
                "mercxclass",
                "Mustang",
            },
            [1] = {
                "cooperworks",
                "TESLAMODELS",
            },
        }
    },
    Recompense = {
        -- Caisse Mai
        ["money_150000"] = { type = "money", message = "Félicitation, vous avez gagner 150000$." },
        ["silv2500hd"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Chevrolet." },
        ["Coins_1000"] = { type = "Coins", message = "Félicitation, vous avez gagner 1000 Coins." },
        ["weapon_machete"] = { type = "weapon", message = "Félicitation, vous avez gagner un Katana." },
        ["m5e60"] = { type = "vehicle", message = "Félicitation, vous avez gagner une BMW M5 E60." },
        ["weapon_vintagepistol"] = { type = "weapon", message = "Félicitation, vous avez gagner un Pistolet Vintage." },
        ["money_50000"] = { type = "money", message = "Félicitation, vous avez gagner 50000$." },
        ["Coins_850"] = { type = "Coins", message = "Félicitation, vous avez gagner 850 Coins." },
        ["Coins_800"] = { type = "Coins", message = "Félicitation, vous avez gagner 800 Coins." },
        ["supra3"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Supra." },
        ["weapon_bottle"] = { type = "weapon", message = "Félicitation, vous avez gagner une Bouteille cassée." },
        ["z419"] = { type = "vehicle", message = "Félicitation, vous avez gagner une BMW Z4." },
        ["Coins_500"] = { type = "Coins", message = "Félicitation, vous avez gagner 500 Coins." },
        ["rmodx6"] = { type = "vehicle", message = "Félicitation, vous avez gagner une BMW X6." },
        ["weapon_golfclub"] = { type = "weapon", message = "Félicitation, vous avez gagner un Club de golf." },
        -- Caisse Diamond
        ["weapon_pumpshotgun"] = { type = "weapon", message = "Félicitation, vous avez gagner un Fusil a Pompe." },
        ["weapon_heavyshotgun"] = { type = "weapon", message = "Félicitation, vous avez gagner un Fusil a Pompe." },
        ["weapon_appistol"] = { type = "weapon", message = "Félicitation, vous avez gagner un Pistolet Mitrailleur." },
        ["weapon_assaultrifle"] = { type = "weapon", message = "Félicitation, vous avez gagner une Ak-47."},
        ["money_1000000"] = { type = "money", message = "Félicitation, vous avez gagner 1000000$." },
        ["Coins_850"] = { type = "Coins", message = "Félicitation, vous avez gagner 850 Coins" },
        ["Coins_500"] = { type = "Coins", message = "Félicitation, vous avez gagner 500 Coins" },
        ["Coins_1250"] = { type = "Coins", message = "Félicitation, vous avez gagner 1250 Coins" },
        ["918"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Porsche 918 Spyder." },
        ["rmodc63amg"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Mercedes-AMG C63." },
        ["chironss"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Bugatti Chiron." },
        ["rmodatlantic"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Bugatti Atlantic." },
        ["rs615"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Audi RS6 2015." },
        ["rs7r"] = { type = "vehicle", message = "Félicitation, vous avez gagner un AUDI RS7 R." },
        ["e36drift"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Voiture de Drift." },
        ["ninjah2"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Moto." },
        ["g65amg"] = { type = "vehicle", message = "Félicitation, vous avez gagner une MERCEDES G65 AMG." },
        ["huayrar"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Pagani." },
        ["r8ppi"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Audi R8." },
        ["mk7"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Golf 7R." },
        ["rs318"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Audi RS3 2018." },
        ["bmws19"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Moto." },
        ["22m5"] = { type = "vehicle", message = "Félicitation, vous avez gagner un BMW 760M." },
        ["brabus500"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Mercedes BRABUS 500." },
        ["brabus800"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Mercedes BRABUS 800." },
        -- CAISSE NOEL
        ["WEAPON_SCAR17FM"] = { type = "weapon", message = "Félicitation, vous avez gagner une SCAR-17."},
        ["Coins_2250"] = { type = "Coins", message = "Félicitation, vous avez gagner 1000 Coins."},
        ["WEAPON_SPECIALCARBINE"] = { type = "weapon", message = "Félicitation, vous avez gagner une Carabine Spéciale."},
        ["WEAPON_COMBATPDW"] = { type = "weapon", message = "Félicitation, vous avez gagner une ADP de Combat."},
        ["vehicleunique"] = { type = "vehunique", message = "Félicitation, vous avez gagner un Véhicule Unique ( Prennez un screen )."},
        ["WEAPON_GADGETPISTOL"] = { type = "weapon", message = "Félicitation, vous avez gagner une Pistolet Cayo."},
        ["WEAPON_SNOWBALL"] = { type = "weapon", message = "Félicitation, vous avez gagner une Boule de Neige."},
        ["Custom_5"] = { type = "custom", message = "Félicitation, vous avez gagner x5 Jeton Custom."},
        ["Custom_3"] = { type = "custom", message = "Félicitation, vous avez gagner x3 Jeton Custom."},
        ["Custom_1"] = { type = "custom", message = "Félicitation, vous avez gagner x1 Jeton Custom."},
        ["q820"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Audi Q8."},
        ["mb250"] = { type = "vehicle", message = "Félicitation, vous avez gagner un MB250."},
        ["survolt"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Survolt."},
        ["senna"] = { type = "vehicle", message = "Félicitation, vous avez gagner un McLaren Senna."},
        ["22m5"] = { type = "vehicle", message = "Félicitation, vous avez gagner une BMW M5E34."},
        ["acz4"] = { type = "vehicle", message = "Félicitation, vous avez gagner une ACZ4."},
        ["supra3"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Toyota Supra."},
        ["16challenger"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Dodge Challenger."},
        ["rs62"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Audi RS6."},
        ["r820"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Audi R8."},
        ["rmodx6"] = { type = "vehicle", message = "Félicitation, vous avez gagner une BMW MX6."},
        -- Caisse Ruby
        ["weapon_combatmg_mk2"] = { type = "weapon", message = "Félicitation, vous avez gagner une Mitrailleuse MK2." },
        ["weapon_mg"] = { type = "weapon", message = "Félicitation, vous avez gagner une Mitrailleuse." },
        ["weapon_combatmg"] = { type = "weapon", message = "Félicitation, vous avez gagner une Mitrailleuse de Combat." },
        ["weapon_marksmanrifle_mk2"] = { type = "weapon", message = "Félicitation, vous avez gagner un Sniper Marksman." },
        ["swift2"] = { type = "helico", message = "Félicitation, vous avez gagner Hélicoptère de Luxe." },
        ["weapon_heavysniper_mk2"] = { type = "weapon", message = "Félicitation, vous avez gagner Sniper Heavy" },
        ["cargobob2"] = { type = "helico", message = "Félicitation, vous avez gagner un Cargobob"},
        ["weapon_assaultshotgun"] = { type = "weapon", message = "Félicitation, vous avez gagner un fusil a pompe d'assault" },
        ["luxor2"] = { type = "helico", message = "Félicitation, vous avez gagner un Jet de luxe." },
        ["buzzard2"] = { type = "helico", message = "Félicitation, vous avez gagner un Buzzard." },
        ["avenger"] = { type = "helico", message = "Félicitation, vous avez gagner un Avenger." },
        ["money_4000000"] = { type = "money", message = "Félicitation, vous avez gagner un 4000000$." },
        ["Coins_500"] = { type = "Coins", message = "Félicitation, vous avez gagner 500 Coins." },
        ["Coins_800"] = { type = "Coins", message = "Félicitation, vous avez gagner 800 Coins." },
        ["Coins_450"] = { type = "Coins", message = "Félicitation, vous avez gagner 450 Coins." },
        ["gls632"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Mercedes GLS 63." },
        ["bmws19"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Moto." },
        ["p1"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Mclaren P1." },
        ["rs6abtp"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Audi RS6 ABT" },
        ["rs666"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Audi RS6." },
        -- CAISSE HALLOWEEN
        ["dune2"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Voiture Halloween." },
        ["speedo2"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Camion Halloween." },
        ["weapon_flaregun"] = { type = "weapon", message = "Félicitation, vous avez gagner un Flare Gun." },
        ["money_2500000"] = { type = "money", message = "Félicitation, vous avez gagner 2.500.000$"},
        ["money_1500000"] = { type = "money", message = "Félicitation, vous avez gagner 1.500.000$" },
        ["BType2"] = { type = "vehicle", message = "Félicitation, vous avez gagner une BType2." },
        ["money_750000"] = { type = "money", message = "Félicitation, vous avez gagner 750.000$" },
        ["Tornado6"] = { type = "vehicle", message = "Félicitation, vous avez gagner Tornado Halloween" },
        -- CAISSE FIDELITE
        ["WEAPON_ASSAULTSHOTGUN"] = { type = "weapon", message = "Félicitation, vous avez gagner un Fusil a pompe d'assault." },
        ["rx7fdbn"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Mazda RX7." },
        ["WEAPON_CASABLANCA"] = { type = "weapon", message = "Félicitation, vous avez gagner une Machete Casa Blanca." },
        ["WEAPON_KATANA"] = { type = "weapon", message = "Félicitation, vous avez gagner un Katana." },
        -- CAISSE VEHICULE
        ["cooperworks"] = { type = "vehicle", message = "Félicitation, vous avez gagner une cooper." },
        ["FCT"] = { type = "vehicle", message = "Félicitation, vous avez gagner une ferrari 2015." },
        ["M3E30"] = { type = "vehicle", message = "Félicitation, vous avez gagner une BMW M3 E30." },
        ["mercxclass"] = { type = "vehicle", message = "Félicitation, vous avez gagner un Mercedes-Benz X-Class." },
        ["Mustang"] = { type = "vehicle", message = "Félicitation, vous avez gagner une mustang." },
        ["PEANUT"] = { type = "vehicle", message = "Félicitation, vous avez gagner une PEANUT." },
        ["MUSTANG"] = { type = "vehicle", message = "Félicitation, vous avez gagner une mustang GT." },
        ["TESLAMODELS"] = { type = "vehicle", message = "Félicitation, vous avez gagner une Tesla model S." },
        ["VIPER"] = { type = "vehicle", message = "Félicitation, vous avez gagner une VIPER." }
    }
}